/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MetaPunkController2022 } from "./MetaPunkController2022";

export { MetaPunkController2022__factory } from "./factories/MetaPunkController2022__factory";
